name: nodejs-starter
# Ensure the workflow runs on schedule (Sunday at 0:00) and on push to the main branch
on:
    # schedule:
    #     - cron: '0 0 * * 0'
    push:
        branches:
        - main
# Use a matrix strategy to use Node.js versions 16.x and 18.x
jobs:
  build-and-test-lint:

    runs-on: ubuntu-latest

    strategy:
        matrix:
            node-version: ['18.x', '20.x']

    steps:
      - name : Check out the code from the repository.
        uses: actions/checkout@v4

      # Set up a Node.js environment using the specified node version.
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Run the linter.
        run: npm run lint

      # Send a console message at completion.
      - run: echo "Hello ${{ github.actor }}. You pushed to ${{ github.repository }} at ${{ github.event.head_commit.timestamp }}."